id: P007120
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14616
  title: མཆན་བརྒྱབ་ལྷན་ཐབས།
  author: ''
  volumes:
    ade0635a3a0e4c73b082faf76d080d88:
      image_group_id: I1KG15621
      title: ''
      volume_number: 1
      total_pages: 662
ebook_metadata:
  title: མཆན་བརྒྱབ་ལྷན་ཐབས།
  author: ''
  sku: P007120
  cover: cover.jpg
  layers:
  - pagination
