id: P007120
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:43:01.478748
source_metadata:
  id: bdr:W1KG14616
  title: མཆན་བརྒྱབ་ལྷན་ཐབས།
  author: ''
  volumes:
    e1b87122fe484edd922b51efd0d12a78:
      image_group_id: I1KG15621
      title: Volume 1 of mchan brgya ba lhan thabs/
      volume_number: 1
      total_pages: 662
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
